import numpy as np

adj = np.load('./adjacency_matrices/trip_counts_201701_201812_top_300.npy')
adj = adj/np.sum(adj,axis=1,keepdims=True)
adj = adj + np.eye(adj.shape[0])

num_time_dims = 2

base_specs = {'save_model': True,
              'save_model_history': True,
              'batch_size': 64,
              'max_epochs': 100,
              'patience': 10,
              'loss_type': 'mae',
              'learning_rate': 1e-3}


def mergeDicts(dict1,dict2=base_specs):

    dict3 = {}
    for key in dict1:
        dict3[key] = dict1[key]
    for key in dict2:
        dict3[key] = dict2[key]

    return dict3


models_to_run = {'LinearRegressor': [mergeDicts({'model_name': 'LinearRegressor', 'model_type': 'LinearRegressor'}),
                                     {'num_nodes': 300,
                                      'num_steps': 10,
                                      'input_features': 4,
                                      'output_features': 2,
                                      'l2_reg': 0.00}],

                 'FNN_noreg': [mergeDicts({'model_name': 'FNN_noreg', 'model_type': 'FNN'}),
                                     {'num_layers': 2,
                                      'units_per_layer':256,
                                      'num_nodes': 300,
                                      'num_steps': 10,
                                      'input_features': 4,
                                      'output_features': 2,
                                      'l2_reg': 0.00}],

                 'FNN_withreg': [mergeDicts({'model_name': 'FNN_withreg', 'model_type': 'FNN'}),
                                     {'num_layers': 2,
                                      'units_per_layer':256,
                                      'num_nodes': 300,
                                      'num_steps': 10,
                                      'input_features': 4,
                                      'output_features': 2,
                                      'l2_reg': 0.001}],

                 'FCLSTM': [mergeDicts({'model_name': 'FCLSTM', 'model_type': 'FCLSTM'}),
                                     {'num_layers': 2,
                                      'units_per_layer':16,
                                      'num_nodes': 300,
                                      'num_steps': 10,
                                      'input_features': 4,
                                      'output_features': 2,
                                      'l2_reg': 0.001}],

                 'STGCN_fixedA': [mergeDicts({'model_name': 'STGCN_fixedA', 'model_type': 'STGCN'}),
                                     {'num_nodes': 300,
                                      'num_steps': 10,
                                      'input_features': 4,
                                      'output_features': 2,
                                      'num_time_dims': num_time_dims,
                                      'num_blocks': 2,
                                      'block_units': [[64,16,64], [32,16,32]],
                                      'block_kernels': [3,3],
                                      'A': adj,
                                      'emb_dim': 32,
                                      'add_identity': False,
                                      'time_modulation': False,
                                      'time_mod_layers': 0,
                                      'time_mod_activations':['relu','tanh'] ,
                                      'additive_modulation': False,
                                      'l2_reg': 0.00}],

                 'STGCN_adaptiveA': [mergeDicts({'model_name': 'STGCN_adaptiveA', 'model_type': 'STGCN'}),
                                     {'num_nodes': 300,
                                      'num_steps': 10,
                                      'input_features': 4,
                                      'output_features': 2,
                                      'num_time_dims': num_time_dims,
                                      'num_blocks': 2,
                                      'block_units': [[64,16,64], [32,16,32]],
                                      'block_kernels': [3,3],
                                      'A': None,
                                      'emb_dim': 32,
                                      'add_identity': True,
                                      'time_modulation': False,
                                      'time_mod_layers': 0,
                                      'time_mod_activations':['relu','tanh'] ,
                                      'additive_modulation': False,
                                      'l2_reg': 0.00}],

                 'STGCN_timeadaptiveA': [mergeDicts({'model_name': 'STGCN_timeadaptiveA', 'model_type': 'STGCN'}),
                                     {'num_nodes': 300,
                                      'num_steps': 10,
                                      'input_features': 4,
                                      'output_features': 2,
                                      'num_time_dims': num_time_dims,
                                      'num_blocks': 2,
                                      'block_units': [[64,16,64], [32,16,32]],
                                      'block_kernels': [3,3],
                                      'A': None,
                                      'emb_dim': 32,
                                      'add_identity': True,
                                      'time_modulation': True,
                                      'time_mod_layers': 1,
                                      'time_mod_activations':['relu','tanh'] ,
                                      'additive_modulation': False,
                                      'l2_reg': 0.00}],

                  'STGCN_timeadditiveA': [mergeDicts({'model_name': 'STGCN_timeadditiveA', 'model_type': 'STGCN'}),
                                     {'num_nodes': 300,
                                      'num_steps': 10,
                                      'input_features': 4,
                                      'output_features': 2,
                                      'num_time_dims': num_time_dims,
                                      'num_blocks': 2,
                                      'block_units': [[64,16,64], [32,16,32]],
                                      'block_kernels': [3,3],
                                      'A': None,
                                      'emb_dim': 32,
                                      'add_identity': True,
                                      'time_modulation': True,
                                      'time_mod_layers': 1,
                                      'time_mod_activations':['relu','linear'] ,
                                      'additive_modulation': True,
                                      'l2_reg': 0.00}],

                  'STGCN_plus': [mergeDicts({'model_name': 'STGCN_plus', 'model_type': 'STGCNPlus'}),
                                     {'num_nodes': 300,
                                      'num_steps': 10,
                                      'input_features': 4,
                                      'output_features': 2,
                                      'num_time_dims': num_time_dims,
                                      'num_blocks': 2,
                                      'block_units': [[64,16,64], [32,16,32]],
                                      'block_kernels': [3,3],
                                      'A': None,
                                      'emb_dim': 32,
                                      'add_identity': True,
                                      'time_modulation': True,
                                      'time_mod_layers': 1,
                                      'time_mod_activations':['relu','tanh'] ,
                                      'additive_modulation': False,
                                      'full_dynamic_adjacency': True,
                                      'l2_reg': 0.00}],

                 'GWN_adaptive': [mergeDicts({'model_name': 'GWN_adaptive', 'model_type': 'GraphWaveNet'}),
                                     {'num_nodes': 300,
                                      'num_steps': 10,
                                      'input_features': 4,
                                      'output_features': 2,
                                      'num_time_dims': num_time_dims,
                                      'emb_dim': 32,
                                      'num_blocks': 4,
                                      'num_layers': 2,
                                      'res_channels': 32,
                                      'skip_channels': 32,
                                      'dilation_channels': 32,
                                      'end_channels': 32,
                                      'time_modulation': False,
                                      'time_mod_layers': 0,
                                      'time_mod_activations': ['relu','tanh'],
                                      'additive_modulation': False,
                                      'kernel_size': 2,
                                      'use_gc': True,
                                      'add_identity': True
                                      }],

                 'GWN_timeadaptive': [mergeDicts({'model_name': 'GWN_timeadaptive', 'model_type': 'GraphWaveNet'}),
                                     {'num_nodes': 300,
                                      'num_steps': 10,
                                      'input_features': 4,
                                      'output_features': 2,
                                      'num_time_dims': num_time_dims,
                                      'emb_dim': 32,
                                      'num_blocks': 4,
                                      'num_layers': 2,
                                      'res_channels': 32,
                                      'skip_channels': 32,
                                      'dilation_channels': 32,
                                      'end_channels': 32,
                                      'time_modulation': True,
                                      'time_mod_layers': 1,
                                      'time_mod_activations': ['relu','tanh'],
                                      'additive_modulation': False,
                                      'kernel_size': 2,
                                      'use_gc': True,
                                      'add_identity': True
                                      }],

                  'GWN_timeadditive': [mergeDicts({'model_name': 'GWN_timeadditive', 'model_type': 'GraphWaveNet'}),
                                     {'num_nodes': 300,
                                      'num_steps': 10,
                                      'input_features': 4,
                                      'output_features': 2,
                                      'num_time_dims': num_time_dims,
                                      'emb_dim': 32,
                                      'num_blocks': 4,
                                      'num_layers': 2,
                                      'res_channels': 32,
                                      'skip_channels': 32,
                                      'dilation_channels': 32,
                                      'end_channels': 32,
                                      'time_modulation': True,
                                      'time_mod_layers': 1,
                                      'time_mod_activations': ['relu','linear'],
                                      'additive_modulation': True,
                                      'kernel_size': 2,
                                      'use_gc': True,
                                      'add_identity': True
                                      }],


                }
